### ISSUE TITLE
Error building this Docker Extension

### ISSUE THREAD

**Issue by ajeetraina** [gefyrahq/gefyra-docker-desktop-extension#1]
I tried to build this Extension, but it is throwing the following error:

```
gefyra-docker-desktop-extension % make build-extension
docker build --tag=gefyra/docker-extension:latest .
[+] Building 2.4s (15/27)
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 37B                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                  0.0s
 => => transferring context: 34B                                                                                                   0.0s
 => resolve image config for docker.io/docker/dockerfile:1.3-labs                                                                  1.1s
 => CACHED docker-image://docker.io/docker/dockerfile:1.3-labs@sha256:250ce669e1aeeb5ffb892b18039c3f0801466536cb4210c8eb2638e6288  0.0s
 => [internal] load .dockerignore                                                                                                  0.0s
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:17.7-alpine3.14                                                            1.1s
 => [client-builder 1/7] FROM docker.io/library/node:17.7-alpine3.14@sha256:539e64749f7dc6c578d744d879fd0ec37f3afe552ae4aca9744cc  0.0s
 => [internal] load build context                                                                                                  0.0s
 => => transferring context: 540B                                                                                                  0.0s
 => [dl 1/5] FROM docker.io/library/alpine                                                                                         0.0s
 => CACHED [stage-3 2/7] COPY docker-compose.yaml .                                                                                0.0s
 => CACHED [stage-3 3/7] COPY metadata.json .                                                                                      0.0s
 => CACHED [stage-3 4/7] COPY docker.svg .                                                                                         0.0s
 => ERROR [stage-3 5/7] COPY gefyra ./gefyra_mac                                                                                   0.0s
------
 > [stage-3 5/7] COPY gefyra ./gefyra_mac:
------
failed to compute cache key: "/gefyra" not found: not found
```

**Comment by SteinRobert** [comment]
Hey @ajeetraina - thank you so much for your interest in Gefyra! This Docker extension is super super work in progress. I guess we should make this clear in the README.md.
Adding Gefyra as a Docker Desktop extension is pretty high on our priority list right now - it will be probably available within the next few weeks. We'll add another comment here once we're in alpha or beta mode :)

**Comment by ajeetraina** [comment]
Hi, @SteinRobert Great to know that this is on your priority to-do list.
Just to let you know that we are here to assist you in case of any issues. 

A dedicated  #extensions channel under Docker Community Slack allows you to connect to the official Docker Extensions Team directly. Feel free to leverage it.

Also, I would love to see it here at https://github.com/collabnix/docker-community-extensions ~ This is a curated list of Docker Extensions built by the open community.

Do let us know once you're done. I would be happy to test it.

**Comment by SteinRobert** [comment]
@ajeetraina we indeed could need some assistance - could you send me an invite to the Docker community? It seems it's not possible to join without an invite. robert@blueshoe.de

**Comment by ajeetraina** [comment]
Can you please join? http://dockr.ly/slack

**Comment by SteinRobert** [comment]
It basically says that only mails from @docker.com and @jackmorton.com are allowed and I should contact an admin.

<img width="456" alt="Bildschirmfoto 2022-08-28 um 11 24 18" src="https://user-images.githubusercontent.com/1231105/187067133-a88e0d3e-46a7-465f-8820-618158a227e1.png">

**Comment by ajeetraina** [comment]
@SteinRobert  Let me start an email thread and help you out.

**Comment by SteinRobert** [comment]
Sure.

**Comment by eeveeta** [comment]
Sorry, the link is fixed now. You should be able to join now.

**Comment by amyb12345** [comment]
You can also email the Extensions team at extensions@docker.com.  Slack is preferred, but email works if Slack is proving challenging.

**Comment by SteinRobert** [comment]
Errors are resolved - working on the marketplace submission now :) Thanks guys!
