### ISSUE TITLE
Error: No command specified

### ISSUE THREAD

**Issue by EvgenyGrishnov** [gefyrahq/gefyra-docker-desktop-extension#36]
Hello. Just trying to run extension for the first time on my local docker-desktop k8s cluster

![image](https://user-images.githubusercontent.com/13975060/220088751-b2e607c3-ea46-4366-bff0-1a3af5ae1640.png)

**Comment by SteinRobert** [comment]
Hey @EvgenyGrishnov thank you for reporting the issue and help us improve Gefyra!
For me it looks like you chose and image without command and did not provide an override command - is that possible?

**Comment by EvgenyGrishnov** [comment]
Works after update somehow. I've tried to run sample dot core service and it works now without the need of setting some command in the field

**Comment by SteinRobert** [comment]
I consider this closed then :)
