### ISSUE TITLE
Error: Wrong labels on the form of container settings

### ISSUE THREAD

**Issue by EvgenyGrishnov** [gefyrahq/gefyra-docker-desktop-extension#61]
![image](https://user-images.githubusercontent.com/13975060/226171988-f23e0147-47f0-4fa0-8c7d-5b8965cca3ee.png)
Must be vise versa: 80 - is port on container, 9999 - port that I've opened on my host. And url would be here: http://localhost:9999

**Comment by SteinRobert** [comment]
Hey @EvgenyGrishnov thank you for reporting this! We will check the issue and get back to you :)

**Comment by SteinRobert** [comment]
@EvgenyGrishnov version 1.1.4 contains a fix. Thank you again for reporting!
